services:
  - type: web
    name: agroobot-tesa
    env: node
    plan: free
    buildCommand: npm run render-build
    startCommand: npm run render-start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_MINI_APP_URL
        sync: false
      - key: DB_PATH
        value: ./server/db/tesa_campo.sqlite
