-- Ejecutar una vez en el SQL Editor de Supabase antes de desplegar esta versión.
-- Migración aditiva: conserva todos los datos y reportes existentes.
BEGIN;
CREATE TABLE IF NOT EXISTS public.empleado (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre TEXT NOT NULL CHECK (length(trim(nombre)) BETWEEN 1 AND 150),
  roles JSONB NOT NULL DEFAULT '[]'::jsonb CHECK (jsonb_typeof(roles) = 'array')
);
ALTER TABLE public.empleado ENABLE ROW LEVEL SECURITY;
GRANT ALL ON public.empleado TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.empleado_id_seq TO service_role;
ALTER TABLE public.reporte_cuadrilla ADD COLUMN IF NOT EXISTS empleados JSONB NOT NULL DEFAULT '[]'::jsonb;
COMMIT;
NOTIFY pgrst, 'reload schema';
