-- AGROKOOL · Esquema inicial PostgreSQL/Supabase
-- Ejecutar en Supabase SQL Editor. No elimina ni modifica SQLite.

create extension if not exists pgcrypto;

create table if not exists public.usuario (
  id bigint generated by default as identity primary key,
  username text not null unique,
  password_hash text not null,
  nombre text not null default '',
  rol text not null default 'campo',
  pin text unique,
  activo boolean not null default true,
  tg_user_id text,
  tg_chat_id text,
  creado_en timestamptz not null default now(),
  actualizado_en timestamptz not null default now()
);

create table if not exists public.proyecto (
  id bigint generated by default as identity primary key,
  nombre text not null,
  tipo text,
  ciclo text,
  fecha_inicio date,
  fecha_fin date,
  superficie_meta_ha numeric(12,2) not null default 0,
  gerente_id bigint references public.usuario(id) on delete set null,
  estado text not null default 'activo',
  creado_en timestamptz not null default now(),
  actualizado_en timestamptz not null default now()
);

create table if not exists public.hito (
  id bigint generated by default as identity primary key,
  proyecto_id bigint not null references public.proyecto(id) on delete cascade,
  nombre text not null,
  descripcion text,
  orden integer not null default 1,
  fecha_meta date,
  superficie_meta_ha numeric(12,2) not null default 0,
  estado text not null default 'pendiente',
  creado_en timestamptz not null default now(),
  actualizado_en timestamptz not null default now()
);

create table if not exists public.tarea (
  id bigint generated by default as identity primary key,
  hito_id bigint not null references public.hito(id) on delete cascade,
  proyecto_id bigint not null references public.proyecto(id) on delete cascade,
  predio_id bigint,
  nombre text not null,
  actividad_id text,
  unidad text default 'ha',
  cantidad_meta numeric(12,2) not null default 0,
  cantidad_acumulada numeric(12,2) not null default 0,
  estado text not null default 'pendiente',
  responsable text,
  creado_en timestamptz not null default now(),
  actualizado_en timestamptz not null default now()
);

create index if not exists idx_hito_proyecto_orden on public.hito(proyecto_id, orden, id);
create index if not exists idx_tarea_hito on public.tarea(hito_id);
create index if not exists idx_tarea_proyecto on public.tarea(proyecto_id);
create index if not exists idx_usuario_pin_activo on public.usuario(pin) where activo = true;

-- Evita que las fechas de actualización dependan de la aplicación.
create or replace function public.set_actualizado_en()
returns trigger language plpgsql as $$
begin
  new.actualizado_en = now();
  return new;
end;
$$;

drop trigger if exists usuario_actualizado_en on public.usuario;
create trigger usuario_actualizado_en before update on public.usuario for each row execute function public.set_actualizado_en();
drop trigger if exists proyecto_actualizado_en on public.proyecto;
create trigger proyecto_actualizado_en before update on public.proyecto for each row execute function public.set_actualizado_en();
drop trigger if exists hito_actualizado_en on public.hito;
create trigger hito_actualizado_en before update on public.hito for each row execute function public.set_actualizado_en();
drop trigger if exists tarea_actualizado_en on public.tarea;
create trigger tarea_actualizado_en before update on public.tarea for each row execute function public.set_actualizado_en();

comment on table public.usuario is 'Usuarios operativos migrados desde SQLite; el backend conserva el hash bcrypt.';
comment on table public.proyecto is 'Proyectos y ciclos agrícolas.';

create table if not exists public.predio (id bigint generated by default as identity primary key, nombre text not null, superficie_legal_ha numeric(12,2) not null default 0, superficie_util_ha numeric(12,2) not null default 0, regimen text, poligono_geojson text);
create table if not exists public.obra (id bigint generated by default as identity primary key, nombre text not null, proyecto_id bigint not null references public.proyecto(id) on delete cascade, fase_actual text, estado text not null default 'operacion', tg_thread_id text);
create table if not exists public.obra_predio (obra_id bigint not null references public.obra(id) on delete cascade, predio_id bigint not null references public.predio(id) on delete cascade, primary key (obra_id, predio_id));
create table if not exists public.reporte (id bigint generated by default as identity primary key, client_uuid text not null unique, proyecto_id bigint references public.proyecto(id) on delete set null, hito_id bigint references public.hito(id) on delete set null, tarea_id bigint references public.tarea(id) on delete set null, obra_id bigint references public.obra(id) on delete set null, recibido_en timestamptz default now(), fecha_operativa date not null, hora_offline text, creado_offline timestamptz, autor_nombre text not null, texto_original text, nota text, estado text not null default 'confirmado', es_sin_actividad boolean not null default false, motivo_sin_actividad text);
create table if not exists public.reporte_linea (id bigint generated by default as identity primary key, reporte_id bigint not null references public.reporte(id) on delete cascade, predio_id bigint references public.predio(id) on delete set null, actividad_id text, cantidad numeric(12,2) not null default 0, unidad text not null default 'ha', cantidad_ha numeric(12,2) not null default 0, fuente text not null default 'campo');
create table if not exists public.reporte_cuadrilla (id bigint generated by default as identity primary key, reporte_id bigint not null references public.reporte(id) on delete cascade, rol_id text not null, headcount integer not null default 0);
create table if not exists public.entidad (id bigint generated by default as identity primary key, nombre text not null unique, tipo text default 'empresa', contacto text, activo boolean not null default true);
create table if not exists public.maquina (id bigint generated by default as identity primary key, codigo text not null unique, nombre text not null default '', tipo text not null default 'tractor', modelo text not null, propietaria_id bigint references public.entidad(id) on delete set null, operadora_id bigint references public.entidad(id) on delete set null, umbral_servicio_hrs numeric(12,2) not null default 300, horometro_actual numeric(12,2) not null default 0, ultimo_servicio_hr numeric(12,2) not null default 0, alerta_mantenimiento boolean not null default false);
create table if not exists public.lectura_maquina (id bigint generated by default as identity primary key, reporte_id bigint not null references public.reporte(id) on delete cascade, maquina_id bigint not null references public.maquina(id) on delete cascade, horometro_inicio numeric(12,2) not null, horometro_fin numeric(12,2) not null, horas_trabajadas numeric(12,2) not null default 0, litros_diesel numeric(12,2) not null default 0);
create table if not exists public.incidencia (id bigint generated by default as identity primary key, folio text not null unique, tipo text not null, obra_id bigint not null references public.obra(id) on delete cascade, estado text not null default 'abierta', abierta_en timestamptz default now(), cerrada_en timestamptz, causa_raiz text);
create table if not exists public.material (id bigint generated by default as identity primary key, obra_id bigint not null references public.obra(id) on delete cascade, nombre text not null, requerido numeric(12,2) not null default 0, en_sitio numeric(12,2) not null default 0, pedido numeric(12,2) not null default 0, unidad text not null default 'pza', eta date);
create table if not exists public.medicion (id bigint generated by default as identity primary key, proyecto_id bigint not null references public.proyecto(id) on delete cascade, hectareas numeric(12,2) not null default 0, fecha date not null, fuente text not null default 'dron', archivo_ruta text);
create table if not exists public.reporte_foto (id bigint generated by default as identity primary key, reporte_id bigint not null references public.reporte(id) on delete cascade, archivo_ruta text not null, url text not null, descripcion text, creado_en timestamptz default now());
create table if not exists public.activo_fijo (id bigint generated by default as identity primary key, codigo text not null unique, nombre text not null, tipo text not null, ubicacion text not null, predio_id bigint references public.predio(id) on delete set null, obra_id bigint references public.obra(id) on delete set null, ultima_lectura_fecha date, estado_operativo text not null default 'operativo');
create table if not exists public.lectura_activo_fijo (id bigint generated by default as identity primary key, activo_fijo_id bigint not null references public.activo_fijo(id) on delete cascade, fecha date not null, reporte_id bigint references public.reporte(id) on delete set null, inspeccionado_por text not null, observaciones text, estado_operativo text not null default 'operativo', creado_en timestamptz default now());

-- Columnas referenciales para Odoo (opcionales)
alter table public.entidad add column if not exists odoo_company_id bigint;
alter table public.predio add column if not exists odoo_partner_id bigint;
alter table public.maquina add column if not exists odoo_fleet_id bigint;
alter table public.material add column if not exists odoo_po_id bigint;
alter table public.usuario add column if not exists odoo_user_id bigint;

-- Sincronización de secuencias identity tras migración inicial masiva
select setval(pg_get_serial_sequence('public.usuario', 'id'), coalesce((select max(id) from public.usuario), 1));
select setval(pg_get_serial_sequence('public.proyecto', 'id'), coalesce((select max(id) from public.proyecto), 1));
select setval(pg_get_serial_sequence('public.hito', 'id'), coalesce((select max(id) from public.hito), 1));
select setval(pg_get_serial_sequence('public.tarea', 'id'), coalesce((select max(id) from public.tarea), 1));
select setval(pg_get_serial_sequence('public.predio', 'id'), coalesce((select max(id) from public.predio), 1));
select setval(pg_get_serial_sequence('public.obra', 'id'), coalesce((select max(id) from public.obra), 1));
select setval(pg_get_serial_sequence('public.entidad', 'id'), coalesce((select max(id) from public.entidad), 1));
select setval(pg_get_serial_sequence('public.maquina', 'id'), coalesce((select max(id) from public.maquina), 1));
select setval(pg_get_serial_sequence('public.reporte', 'id'), coalesce((select max(id) from public.reporte), 1));
select setval(pg_get_serial_sequence('public.reporte_linea', 'id'), coalesce((select max(id) from public.reporte_linea), 1));
select setval(pg_get_serial_sequence('public.reporte_cuadrilla', 'id'), coalesce((select max(id) from public.reporte_cuadrilla), 1));
select setval(pg_get_serial_sequence('public.lectura_maquina', 'id'), coalesce((select max(id) from public.lectura_maquina), 1));
select setval(pg_get_serial_sequence('public.incidencia', 'id'), coalesce((select max(id) from public.incidencia), 1));
select setval(pg_get_serial_sequence('public.material', 'id'), coalesce((select max(id) from public.material), 1));
select setval(pg_get_serial_sequence('public.medicion', 'id'), coalesce((select max(id) from public.medicion), 1));
select setval(pg_get_serial_sequence('public.reporte_foto', 'id'), coalesce((select max(id) from public.reporte_foto), 1));
select setval(pg_get_serial_sequence('public.activo_fijo', 'id'), coalesce((select max(id) from public.activo_fijo), 1));
select setval(pg_get_serial_sequence('public.lectura_activo_fijo', 'id'), coalesce((select max(id) from public.lectura_activo_fijo), 1));
